use role accountadmin;

ALTER ACCOUNT UNSET NETWORK_POLICY;

CREATE OR REPLACE NETWORK POLICY my_network_policy
ALLOWED_IP_LIST = ('0.0.0.0');

ALTER ACCOUNT SET NETWORK_POLICY = my_network_policy;

REVOKE ROLE ACCOUNTADMIN FROM USER user;
